/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/Soldier.glb -o src/components/Soldier.jsx -r public 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Soldier(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/models/Soldier.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Root_Scene">
        <group name="RootNode">
          <group name="Armature">
            <primitive object={nodes.hips} />
            <primitive object={nodes.kneeIKL} />
            <primitive object={nodes.ellbowIKL} />
            <primitive object={nodes.wristIKL} />
            <primitive object={nodes.kneeIKR} />
            <primitive object={nodes.ellbowIKR} />
            <primitive object={nodes.wristIKR} />
            <primitive object={nodes.ankleIKL} />
            <primitive object={nodes.ankleIKR} />
          </group>
          <skinnedMesh name="M4_Amo" geometry={nodes.M4_Amo.geometry} material={materials['Material.001']} skeleton={nodes.M4_Amo.skeleton} position={[-20.538, 22.989, -1.293]} rotation={[0.006, -0.106, -1.511]} scale={19.555} />
          <skinnedMesh name="M4" geometry={nodes.M4.geometry} material={materials['Material.001']} skeleton={nodes.M4.skeleton} position={[-20.484, 22.996, 1.314]} rotation={[0.006, -0.106, -1.511]} scale={19.555} />
          <group name="Soldat" rotation={[-Math.PI / 2, 0, 0]} scale={[380.911, 291.389, 278.168]}>
            <skinnedMesh name="Soldat_1" geometry={nodes.Soldat_1.geometry} material={materials['Characters_For_Andrew:lambert']} skeleton={nodes.Soldat_1.skeleton} />
            <skinnedMesh name="Soldat_2" geometry={nodes.Soldat_2.geometry} material={materials['Material.001']} skeleton={nodes.Soldat_2.skeleton} />
            <skinnedMesh name="Soldat_3" geometry={nodes.Soldat_3.geometry} material={materials['Material.003']} skeleton={nodes.Soldat_3.skeleton} />
            <skinnedMesh name="Soldat_4" geometry={nodes.Soldat_4.geometry} material={materials['Material.002']} skeleton={nodes.Soldat_4.skeleton} />
            <skinnedMesh name="Soldat_5" geometry={nodes.Soldat_5.geometry} material={materials['Material.004']} skeleton={nodes.Soldat_5.skeleton} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/Soldier.glb')
